// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Andrew":return img`
........................................
........................................
...................fff..................
............f..fffffffff................
.........fffffffeffffffffff.............
........ffffeeffffefffeeeff.............
.......ffeefffffffffeeefff..............
.......feeffeeefeeeeeeeef...............
.......feffefffffffefffff...............
......fffeef1111111f11111f..............
.....fdddfdf1111111f11111f..............
.....fdffddf11fff11f1fff1f..............
.....fdddfdf11fff11f1fff1f..............
.....fdddddf11fff11fffffff..............
......fddddf1111111fddddddf.............
.......fffdf1111111fddddddf.............
.........fddfffffffdddddddf.............
.........fdddddddddddfffff..............
.........fdddfdddddddbbf................
.........fdffdddddddfddf................
.........fdddfffffffdddf................
.........fdddddddddddddf................
..........fdddddddddddf.................
...........fffffffffff..................
..............fbbbbf....................
..............fddddf....................
.............ffddddf....................
............f2ffffff....................
............f222222f....................
...........f222f222ff...................
...........f222f222f2f.fff..............
..........f222f2222f22fdfdf.............
..........fffff2222f22fddff.............
.........fbddddf222ff2fdfdf.............
........fbfdfdffffff.ffbbf..............
.........fbfdf88888f...ff...............
..........ffffffffff....................
............fbdf.fbdf...................
............ffffffffff..................
............feeeeeeeef..................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
